[package]
name = "project-age"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
chrono = "0.4.42"
futures = "0.3.31"
plotters = "0.3.7"
tokio = { version = "1.47.1", features = ["full"] }
